[features]
seeds = false
skip-lint = false
[programs.localnet]
refi = "Bbh4WYdgbM5vL1YTpk9rAd1R9KXyuC4Y9rrLrWU74zck"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/manice/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
